import { Ocorrencia } from "../types/Ocorrencia";

export const ocorrenciasMock: Ocorrencia[] = [
  {
    id: 1,
    trecho: "BR-101 km 312",
    local: "Acostamento esquerdo",
    descricao: "Vegetação com crescimento acentuado, ultrapassando 30cm. Visibilidade da sinalização de curva comprometida. Sensor registrou distância de 8cm indicando crescimento crítico. Requer roçagem urgente.",
    risco: "alto",
    data: "2025-06-14T08:14:00",
    umidadeSensor: 82,
    distanciaCm: 8,
    validadoPorCamera: true,
    status: "pendente",
    operador: "Carlos Mendes",
  },
  {
    id: 2,
    trecho: "SP-070 km 88",
    local: "Marginal direita",
    descricao: "Crescimento moderado de gramíneas. Sensor indica distância de 18cm. Monitorar evolução nos próximos dias antes de acionar equipe de roçagem.",
    risco: "medio",
    data: "2025-06-13T14:30:00",
    umidadeSensor: 64,
    distanciaCm: 18,
    validadoPorCamera: true,
    status: "em_andamento",
    operador: "Ana Paula",
  },
  {
    id: 3,
    trecho: "BR-116 km 204",
    local: "Canteiro central",
    descricao: "Vegetação dentro do padrão. Sensor com leitura estável de 28cm. Roçagem realizada há 10 dias, rebrota normal para o período.",
    risco: "baixo",
    data: "2025-06-12T10:00:00",
    umidadeSensor: 41,
    distanciaCm: 28,
    validadoPorCamera: true,
    status: "resolvido",
    operador: "João Silva",
  },
  {
    id: 4,
    trecho: "SP-070 km 52",
    local: "Acostamento direito",
    descricao: "Roçagem realizada há 15 dias. Rebrota dentro do esperado. Sensor com leitura estável de 26cm.",
    risco: "baixo",
    data: "2025-06-11T09:20:00",
    umidadeSensor: 38,
    distanciaCm: 26,
    validadoPorCamera: false,
    status: "resolvido",
    operador: "Maria Costa",
  },
  {
    id: 5,
    trecho: "BR-381 km 445",
    local: "Talude lado direito",
    descricao: "Vegetação densa obstruindo visão de placa de pedágio. Sensor com distância crítica de 5cm. Necessária intervenção imediata.",
    risco: "alto",
    data: "2025-06-14T06:50:00",
    umidadeSensor: 90,
    distanciaCm: 5,
    validadoPorCamera: false,
    status: "pendente",
    operador: "Carlos Mendes",
  },
  {
    id: 6,
    trecho: "SP-310 km 22",
    local: "Canteiro central",
    descricao: "Crescimento uniforme detectado pelo sensor (14cm). Equipe de campo verificou e classificou como médio. Agendada roçagem para próxima semana.",
    risco: "medio",
    data: "2025-06-10T11:45:00",
    umidadeSensor: 55,
    distanciaCm: 14,
    validadoPorCamera: true,
    status: "em_andamento",
    operador: "Ana Paula",
  },
];

export const alertasIoTMock = [
  { sensorId: "SNS-BR101-312", trecho: "BR-101 km 312", distanciaCm: 8,  risco: "alto"  as const },
  { sensorId: "SNS-BR381-445", trecho: "BR-381 km 445", distanciaCm: 5,  risco: "alto"  as const },
  { sensorId: "SNS-SP070-088", trecho: "SP-070 km 88",  distanciaCm: 18, risco: "medio" as const },
];
